# -*- coding: utf-8 -*-
"""Skripsi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVe--W40yFXyLWTQerS10tJuleslKhSy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

file = "/content/drive/MyDrive/Hawa Esanda/Latihan UV Vis 21 Juli 2022.xlsx"

df = pd.read_excel(file)

print(df.shape)
df.head()

"""Cleaning data"""

drop_cols = [
    'No.',
    'Type',
    'Date/Time',
    'Note',
    'Unnamed: 186'
]

for col in drop_cols:
    if col in df.columns:
        df.drop(columns=col, inplace=True)

print(df.shape)
df.head()

def transform_data(dataframe):

    rows = []

    wavelength_cols = [
        col for col in dataframe.columns
        if col != 'Name'
    ]

    for i in range(len(dataframe)):

        for col in wavelength_cols:

            rows.append([
                float(col),
                dataframe.iloc[i][col]
            ])

    return pd.DataFrame(
        rows,
        columns=[
            'Wavelength',
            'Absorbance'
        ]
    )

"""Skenario 1 : train sampel 123 test 4"""

train_1 = df[
    df['Name'].isin([
        'UV 1264',
        'UV 1265',
        'UV 1266'
    ])
]

test_1 = df[
    df['Name'] == 'UV 1267'
]

train_1_long = transform_data(train_1)

test_1_long = transform_data(test_1)

print(train_1_long.shape)
print(test_1_long.shape)

X_train_1 = train_1_long[['Wavelength']]
y_train_1 = train_1_long['Absorbance']

X_test_1 = test_1_long[['Wavelength']]
y_test_1 = test_1_long['Absorbance']

"""Linear regression"""

linear = LinearRegression()

linear.fit(
    X_train_1,
    y_train_1
)

pred_linear_1 = linear.predict(
    X_test_1
)

"""Evaluasi"""

r2_linear_1 = r2_score(
    y_test_1,
    pred_linear_1
)

rmse_linear_1 = np.sqrt(
    mean_squared_error(
        y_test_1,
        pred_linear_1
    )
)

print("=== LINEAR REGRESSION ===")
print("R² :", r2_linear_1)
print("RMSE :", rmse_linear_1)

"""Polynomial"""

poly = Pipeline([

    (
        'poly',
        PolynomialFeatures(
            degree=2
        )
    ),

    (
        'model',
        LinearRegression()
    )

])

poly.fit(
    X_train_1,
    y_train_1
)

pred_poly_1 = poly.predict(
    X_test_1
)

r2_poly_1 = r2_score(
    y_test_1,
    pred_poly_1
)

rmse_poly_1 = np.sqrt(
    mean_squared_error(
        y_test_1,
        pred_poly_1
    )
)

print("=== POLYNOMIAL REGRESSION ===")
print("R² :", r2_poly_1)
print("RMSE :", rmse_poly_1)

"""Random forest"""

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(
    X_train_1,
    y_train_1
)

pred_rf_1 = rf.predict(
    X_test_1
)

r2_rf_1 = r2_score(
    y_test_1,
    pred_rf_1
)

rmse_rf_1 = np.sqrt(
    mean_squared_error(
        y_test_1,
        pred_rf_1
    )
)

print("=== RANDOM FOREST ===")
print("R² :", r2_rf_1)
print("RMSE :", rmse_rf_1)

hasil_uv1267 = pd.DataFrame({

    'Model': [
        'Linear Regression',
        'Polynomial Regression',
        'Random Forest'
    ],

    'R2': [
        r2_linear_1,
        r2_poly_1,
        r2_rf_1
    ],

    'RMSE': [
        rmse_linear_1,
        rmse_poly_1,
        rmse_rf_1
    ]

})

print(hasil_uv1267)

plt.figure(figsize=(12,6))

plt.plot(
    X_test_1['Wavelength'],
    y_test_1,
    label='Actual UV1267',
    linewidth=3
)

plt.plot(
    X_test_1['Wavelength'],
    pred_linear_1,
    label='Linear'
)

plt.plot(
    X_test_1['Wavelength'],
    pred_poly_1,
    label='Polynomial'
)

plt.plot(
    X_test_1['Wavelength'],
    pred_rf_1,
    label='Random Forest'
)

plt.xlabel("Wavelength")
plt.ylabel("Absorbance")

plt.title(
    "Prediction of UV1267"
)

plt.legend()
plt.grid()

plt.show()

"""Skenario 2 : train sampel 1,2,3,4 test sampel 5"""

train_2 = df[
    df['Name'].isin([
        'UV 1264',
        'UV 1265',
        'UV 1266',
        'UV 1267'
    ])
]

test_2 = df[
    df['Name'] == 'UV 1268'
]

train_2_long = transform_data(train_2)

test_2_long = transform_data(test_2)

print(train_2_long.shape)
print(test_2_long.shape)

X_train_2 = train_2_long[['Wavelength']]

y_train_2 = train_2_long['Absorbance']

X_test_2 = test_2_long[['Wavelength']]

y_test_2 = test_2_long['Absorbance']

"""Linear regression"""

linear = LinearRegression()

linear.fit(
    X_train_2,
    y_train_2
)

pred_linear_2 = linear.predict(
    X_test_2
)

r2_score(
    y_test_2,
    pred_linear_2
)

"""Polynomial"""

poly = Pipeline([

    (
        'poly',
        PolynomialFeatures(
            degree=2
        )
    ),

    (
        'model',
        LinearRegression()
    )

])

poly.fit(
    X_train_2,
    y_train_2
)

pred_poly_2 = poly.predict(
    X_test_2
)

# Evaluasi
r2_poly_2 = r2_score(
    y_test_2,
    pred_poly_2
)

rmse_poly_2 = np.sqrt(
    mean_squared_error(
        y_test_2,
        pred_poly_2
    )
)

print("=== POLYNOMIAL REGRESSION ===")
print("R² :", r2_poly_2)
print("RMSE :", rmse_poly_1)

"""random forest"""

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(
    X_train_2,
    y_train_2
)

pred_rf_2 = rf.predict(
    X_test_2
)

# evaluasi
r2_rf_2 = r2_score(
    y_test_2,
    pred_rf_2
)

rmse_rf_2 = np.sqrt(
    mean_squared_error(
        y_test_2,
        pred_rf_2
    )
)

print("=== RANDOM FOREST ===")
print("R² :", r2_rf_2)
print("RMSE :", rmse_rf_2)

"""### Langkah Perbaikan: Normalisasi Min-Max per Sampel
Kita akan menormalisasi setiap baris agar memiliki nilai minimum 0 dan maksimum 1 sebelum ditransformasi ke format long.
"""

def normalize_spectra(dataframe):
    # Pisahkan kolom Name
    names = dataframe['Name']
    spectra = dataframe.drop(columns=['Name'])

    # Normalisasi Min-Max per baris
    normalized = spectra.apply(lambda x: (x - x.min()) / (x.max() - x.min()), axis=1)

    # Gabungkan kembali
    normalized.insert(0, 'Name', names)
    return normalized

# Terapkan pada dataset awal
df_norm = normalize_spectra(df)

# Visualisasi perbandingan setelah normalisasi
plt.figure(figsize=(10, 5))
for i in range(len(df_norm)):
    plt.plot(df_norm.columns[1:].astype(float), df_norm.iloc[i, 1:], label=df_norm.iloc[i]['Name'])

plt.title("Spektrum Setelah Normalisasi Min-Max")
plt.legend()
plt.show()

"""### Melatih Ulang Model dengan Data Ternormalisasi (Skenario 1)
Kita akan menggunakan `df_norm` untuk memisahkan kembali data training (UV 1264-1266) dan data test (UV 1267).
"""

# 1. Split data dari df_norm
train_norm = df_norm[df_norm['Name'].isin(['UV 1264', 'UV 1265', 'UV 1266'])]
test_norm = df_norm[df_norm['Name'] == 'UV 1267']

# 2. Transform ke format long
train_norm_long = transform_data(train_norm)
test_norm_long = transform_data(test_norm)

X_train_n = train_norm_long[['Wavelength']]
y_train_n = train_norm_long['Absorbance']
X_test_n = test_norm_long[['Wavelength']]
y_test_n = test_norm_long['Absorbance']

# 3. Re-fit Random Forest (sebagai contoh model terbaik sebelumnya)
rf_norm = RandomForestRegressor(n_estimators=100, random_state=42)
rf_norm.fit(X_train_n, y_train_n)
pred_rf_n = rf_norm.predict(X_test_n)

# 4. Evaluasi
r2_n = r2_score(y_test_n, pred_rf_n)
rmse_n = np.sqrt(mean_squared_error(y_test_n, pred_rf_n))

print(f"=== HASIL SETELAH NORMALISASI (RF) ===")
print(f"R² : {r2_n:.4f}")
print(f"RMSE : {rmse_n:.4f}")

# Visualisasi
plt.figure(figsize=(10,5))
plt.plot(X_test_n['Wavelength'], y_test_n, label='Actual (Normalized)', linewidth=2)
plt.plot(X_test_n['Wavelength'], pred_rf_n, label='Predicted (Normalized)', linestyle='--')
plt.legend()
plt.title("Prediksi UV 1267 Setelah Normalisasi")
plt.show()

"""### Polynomial Regression dengan Data Ternormalisasi
Kita akan menggunakan `X_train_n` dan `y_train_n` yang sudah dinormalisasi sebelumnya.
"""

# Inisialisasi dan training Polynomial Regression
poly_norm = Pipeline([
    ('poly', PolynomialFeatures(degree=2)),
    ('model', LinearRegression())
])

poly_norm.fit(X_train_n, y_train_n)
pred_poly_n = poly_norm.predict(X_test_n)

# Evaluasi
r2_poly_n = r2_score(y_test_n, pred_poly_n)
rmse_poly_n = np.sqrt(mean_squared_error(y_test_n, pred_poly_n))

print(f"=== HASIL SETELAH NORMALISASI (Polynomial) ===")
print(f"R2 : {r2_poly_n:.4f}")
print(f"RMSE : {rmse_poly_n:.4f}")

# Visualisasi perbandingan
plt.figure(figsize=(10,5))
plt.plot(X_test_n['Wavelength'], y_test_n, label='Actual (Normalized)', linewidth=2)
plt.plot(X_test_n['Wavelength'], pred_poly_n, label='Predicted (Poly Norm)', linestyle='--', color='orange')
plt.legend()
plt.title("Prediksi UV 1267 (Polynomial) Setelah Normalisasi")
plt.show()

"""### Polynomial Regression Derajat 3
Menggunakan derajat yang lebih tinggi untuk mencoba menangkap detail spektrum yang lebih kompleks.
"""

# Inisialisasi dan training Polynomial Regression derajat 3
poly_deg3 = Pipeline([
    ('poly', PolynomialFeatures(degree=3)),
    ('model', LinearRegression())
])

poly_deg3.fit(X_train_n, y_train_n)
pred_poly3_n = poly_deg3.predict(X_test_n)

# Evaluasi
r2_poly3_n = r2_score(y_test_n, pred_poly3_n)
rmse_poly3_n = np.sqrt(mean_squared_error(y_test_n, pred_poly3_n))

print(f"=== HASIL NORMALISASI (Polynomial Degree 3) ===")
print(f"R2 : {r2_poly3_n:.4f}")
print(f"RMSE : {rmse_poly3_n:.4f}")

# Visualisasi
plt.figure(figsize=(10,5))
plt.plot(X_test_n['Wavelength'], y_test_n, label='Actual (Normalized)', linewidth=2)
plt.plot(X_test_n['Wavelength'], pred_poly3_n, label='Predicted (Poly Deg 3)', linestyle='--', color='green')
plt.legend()
plt.title("Prediksi UV 1267 (Polynomial Degree 3)")
plt.show()

"""Sekarang distribusinya sudah lebih seragam. Anda bisa mengulangi proses training menggunakan `df_norm` untuk melihat apakah nilai R² membaik.

### Langkah Perbaikan: StandardScaler (Z-score) per Sampel
Kita akan mencoba standardisasi agar setiap sampel memiliki mean 0 dan standar deviasi 1.
"""

from sklearn.preprocessing import StandardScaler

def standardize_spectra(dataframe):
    names = dataframe['Name']
    spectra = dataframe.drop(columns=['Name'])

    # Standardize per baris (transpos dulu karena StandardScaler bekerja per kolom)
    scaler = StandardScaler()
    standardized = pd.DataFrame(
        scaler.fit_transform(spectra.T).T,
        columns=spectra.columns,
        index=spectra.index
    )

    standardized.insert(0, 'Name', names)
    return standardized

# Terapkan standardisasi
df_std = standardize_spectra(df)

# Visualisasi
plt.figure(figsize=(10, 5))
for i in range(len(df_std)):
    plt.plot(df_std.columns[1:].astype(float), df_std.iloc[i, 1:], label=df_std.iloc[i]['Name'])

plt.title("Spektrum Setelah StandardScaler (Z-score)")
plt.legend()
plt.grid(True)
plt.show()

"""### Evaluasi Model (Polynomial Degree 2) dengan StandardScaler
Mari kita uji pada Skenario 1 (Train: 1264-1266, Test: 1267).
"""

# 1. Split data dari df_std
train_std = df_std[df_std['Name'].isin(['UV 1264', 'UV 1265', 'UV 1266'])]
test_std = df_std[df_std['Name'] == 'UV 1267']

# 2. Transform ke format long
train_std_long = transform_data(train_std)
test_std_long = transform_data(test_std)

X_train_s = train_std_long[['Wavelength']]
y_train_s = train_std_long['Absorbance']
X_test_s = test_std_long[['Wavelength']]
y_test_s = test_std_long['Absorbance']

# 3. Fit Polynomial Regression Degree 2
poly_std = Pipeline([
    ('poly', PolynomialFeatures(degree=2)),
    ('model', LinearRegression())
])

poly_std.fit(X_train_s, y_train_s)
pred_poly_s = poly_std.predict(X_test_s)

# 4. Evaluasi
r2_s = r2_score(y_test_s, pred_poly_s)
rmse_s = np.sqrt(mean_squared_error(y_test_s, pred_poly_s))

print(f"=== HASIL SETELAH STANDARD-SCALER (Poly Deg 2) ===")
print(f"R² : {r2_s:.4f}")
print(f"RMSE : {rmse_s:.4f}")

# Perbandingan dengan hasil Min-Max sebelumnya
print(f"\n(Perbandingan) R² Min-Max sebelumnya: {r2_poly_n:.4f}")

"""### Perbandingan: Random Forest dengan StandardScaler (Z-score)
Mari kita lihat apakah Random Forest juga mengalami peningkatan signifikan dengan normalisasi Z-score.
"""

# Inisialisasi dan training Random Forest pada data standardized
rf_std = RandomForestRegressor(n_estimators=100, random_state=42)
rf_std.fit(X_train_s, y_train_s)
pred_rf_s = rf_std.predict(X_test_s)

# Evaluasi
r2_rf_s = r2_score(y_test_s, pred_rf_s)
rmse_rf_s = np.sqrt(mean_squared_error(y_test_s, pred_rf_s))

print(f"=== HASIL SETELAH STANDARD-SCALER (Random Forest) ===")
print(f"R% : {r2_rf_s:.4f}")
print(f"RMSE : {rmse_rf_s:.4f}")

# Visualisasi perbandingan prediksi
plt.figure(figsize=(10,5))
plt.plot(X_test_s['Wavelength'], y_test_s, label='Actual (Standardized)', linewidth=2, color='black')
plt.plot(X_test_s['Wavelength'], pred_poly_s, label='Poly Deg 2 Pred', linestyle='--', color='orange')
plt.plot(X_test_s['Wavelength'], pred_rf_s, label='Random Forest Pred', linestyle=':', color='red')
plt.legend()
plt.title("Perbandingan Prediksi: Poly vs RF (Z-score Normalization)")
plt.grid(True)
plt.show()

"""### Perbandingan: Linear Regression dengan StandardScaler (Z-score)
Mari kita uji performa baseline Linear Regression pada data yang sudah ternormalisasi.
"""

# Inisialisasi dan training Linear Regression pada data standardized
linear_std = LinearRegression()
linear_std.fit(X_train_s, y_train_s)
pred_linear_s = linear_std.predict(X_test_s)

# Evaluasi
r2_linear_s = r2_score(y_test_s, pred_linear_s)
rmse_linear_s = np.sqrt(mean_squared_error(y_test_s, pred_linear_s))

print(f"=== HASIL SETELAH STANDARD-SCALER (Linear Regression) ===")
print(f"R2 : {r2_linear_s:.4f}")
print(f"RMSE : {rmse_linear_s:.4f}")

# Perbandingan akhir semua model dengan Z-score
summary_std = pd.DataFrame({
    'Model': ['Linear Regression', 'Polynomial (Deg 2)', 'Random Forest'],
    'R2 (Z-score)': [r2_linear_s, r2_s, r2_rf_s]
})
display(summary_std)

"""### Validasi Akhir: Skenario 2 (Test: UV 1268) dengan Linear + Z-score
Kita akan menggunakan data training UV 1264-1267 dan menguji pada UV 1268 menggunakan normalisasi StandardScaler.
"""

# 1. Split data dari df_std (Scenario 2)
train_std_2 = df_std[df_std['Name'].isin(['UV 1264', 'UV 1265', 'UV 1266', 'UV 1267'])]
test_std_2 = df_std[df_std['Name'] == 'UV 1268']

# 2. Transform ke format long
train_std_long_2 = transform_data(train_std_2)
test_std_long_2 = transform_data(test_std_2)

X_train_s2 = train_std_long_2[['Wavelength']]
y_train_s2 = train_std_long_2['Absorbance']
X_test_s2 = test_std_long_2[['Wavelength']]
y_test_s2 = test_std_long_2['Absorbance']

# 3. Fit Linear Regression
linear_v = LinearRegression()
linear_v.fit(X_train_s2, y_train_s2)
pred_v = linear_v.predict(X_test_s2)

# 4. Evaluasi
r2_v = r2_score(y_test_s2, pred_v)
rmse_v = np.sqrt(mean_squared_error(y_test_s2, pred_v))

print(f"=== VALIDASI SKENARIO 2 (UV 1268) ===")
print(f"R2 : {r2_v:.4f}")
print(f"RMSE : {rmse_v:.4f}")

# 5. Visualisasi Hasil Akhir
plt.figure(figsize=(10, 5))
plt.plot(X_test_s2['Wavelength'], y_test_s2, label='Actual UV 1268 (Std)', color='black', linewidth=2)
plt.plot(X_test_s2['Wavelength'], pred_v, label='Linear Prediction', linestyle='--', color='blue')
plt.title("Validasi Akhir pada UV 1268 (Linear Regression + Z-score)")
plt.legend()
plt.grid(True)
plt.show()

"""### Perbandingan Akhir Skenario 1 (Z-score)
Visualisasi perbandingan prediksi Linear Regression, Polynomial Degree 2, dan Random Forest terhadap data aktual UV 1267.
"""

plt.figure(figsize=(12, 6))

# Data Aktual
plt.plot(X_test_s['Wavelength'], y_test_s, label='Actual UV 1267 (Std)', color='black', linewidth=3, alpha=0.7)

# Prediksi Model
plt.plot(X_test_s['Wavelength'], pred_linear_s, label=f'Linear Regression (R2: {r2_linear_s:.3f})', linestyle='--')
plt.plot(X_test_s['Wavelength'], pred_poly_s, label=f'Polynomial Deg 2 (R2: {r2_s:.3f})', linestyle='-.')
plt.plot(X_test_s['Wavelength'], pred_rf_s, label=f'Random Forest (R2: {r2_rf_s:.3f})', linestyle=':')

plt.title("Perbandingan Prediksi Model pada Skenario 1 (Z-score Normalization)")
plt.xlabel("Wavelength")
plt.ylabel("Absorbance (Standardized)")
plt.legend()
plt.grid(True, which='both', linestyle='--', alpha=0.5)
plt.show()

# Tampilkan tabel ringkasan kembali
display(summary_std)

import pandas as pd

# Save the evaluation summary to a CSV file
summary_std.to_csv('model_evaluation_summary.csv', index=False)

print("Evaluation results saved to 'model_evaluation_summary.csv'.")
# Display the saved file content to verify
display(pd.read_csv('model_evaluation_summary.csv'))

"""### Perbandingan Ketiga Model pada Skenario 2 (Test: UV 1268)
Kita akan melatih Linear Regression, Polynomial Degree 2, dan Random Forest menggunakan data training Skenario 2 yang sudah di-standardisasi (Z-score).
"""

# 1. Inisialisasi Model
model_linear_2 = LinearRegression()
model_poly_2 = Pipeline([
    ('poly', PolynomialFeatures(degree=2)),
    ('model', LinearRegression())
])
model_rf_2 = RandomForestRegressor(n_estimators=100, random_state=42)

# 2. Training Model pada X_train_s2 dan y_train_s2
model_linear_2.fit(X_train_s2, y_train_s2)
model_poly_2.fit(X_train_s2, y_train_s2)
model_rf_2.fit(X_train_s2, y_train_s2)

# 3. Prediksi pada X_test_s2
pred_linear_v2 = model_linear_2.predict(X_test_s2)
pred_poly_v2 = model_poly_2.predict(X_test_s2)
pred_rf_v2 = model_rf_2.predict(X_test_s2)

# 4. Hitung Skor R2
r2_linear_v2 = r2_score(y_test_s2, pred_linear_v2)
r2_poly_v2 = r2_score(y_test_s2, pred_poly_v2)
r2_rf_v2 = r2_score(y_test_s2, pred_rf_v2)

# 5. Ringkasan Hasil Skenario 2
summary_v2 = pd.DataFrame({
    'Model': ['Linear Regression', 'Polynomial (Deg 2)', 'Random Forest'],
    'R2 (Scenario 2)': [r2_linear_v2, r2_poly_v2, r2_rf_v2]
})

# 6. Visualisasi
plt.figure(figsize=(12, 6))
plt.plot(X_test_s2['Wavelength'], y_test_s2, label='Actual UV 1268 (Std)', color='black', linewidth=3, alpha=0.7)
plt.plot(X_test_s2['Wavelength'], pred_linear_v2, label=f'Linear (R2: {r2_linear_v2:.3f})', linestyle='--')
plt.plot(X_test_s2['Wavelength'], pred_poly_v2, label=f'Poly Deg 2 (R2: {r2_poly_v2:.3f})', linestyle='-.')
plt.plot(X_test_s2['Wavelength'], pred_rf_v2, label=f'Random Forest (R2: {r2_rf_v2:.3f})', linestyle=':')

plt.title("Perbandingan Model pada Skenario 2 (UV 1268 - Z-score)")
plt.xlabel("Wavelength")
plt.ylabel("Absorbance (Standardized)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

display(summary_v2)

# Save Scenario 2 evaluation summary to a CSV file
summary_v2.to_csv('model_evaluation_scenario_2.csv', index=False)

print("Scenario 2 evaluation results saved to 'model_evaluation_scenario_2.csv'.")
# Display the saved file content to verify
display(pd.read_csv('model_evaluation_scenario_2.csv'))

"""### Perbandingan Performa: Skenario 1 vs Skenario 2
Kita akan menggabungkan hasil R² dari kedua skenario untuk melihat stabilitas model.
"""

# Menyiapkan data untuk perbandingan
comparison_df = summary_std.copy()
comparison_df['R2 (Scenario 2)'] = summary_v2['R2 (Scenario 2)']
comparison_df.columns = ['Model', 'Scenario 1 (UV 1267)', 'Scenario 2 (UV 1268)']

# Reshape data untuk plotting
plot_data = comparison_df.set_index('Model').T

# Visualisasi
ax = plot_data.plot(kind='bar', figsize=(10, 6), rot=0)
plt.title("Perbandingan Nilai R²: Skenario 1 vs Skenario 2")
plt.ylabel("R² Score")
plt.ylim(0, 1.0) # Fokus pada range positif
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.legend(title="Model")

# Tambahkan label nilai di atas bar
for p in ax.patches:
    ax.annotate(f'{p.get_height():.3f}',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center',
                xytext=(0, 9),
                textcoords='offset points')

plt.tight_layout()
plt.show()

display(comparison_df)